### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by elifoster** [tokuhirom/node-perl#11]
Running the code:

```
var Perl = require('perl').Perl();
var perl = new Perl();

perl.Run({
    script : '../main.pl',
    args : []
});
```

Returns the following error:

```
dlopen(libperl.a, 9): image not found

/Users/~~~/Desktop/Stuff/Dev/Perl/GHULS/src/main.js:2
var perl = new Perl();
           ^
TypeError: object is not a function
    at Object.<anonymous> (/Users/~~~/Desktop/Stuff/Dev/Perl/GHULS/src/main.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Paths snipped for my privacy.

**Comment by viatsko** [comment]
libperl is statically linked in this case, removing InitPerl stuff from `.cc` file should help in your case
