### ISSUE TITLE
Not able to install with Node v5.9.0 and Perl 5.18.2

### ISSUE THREAD

**Issue by kidambisrinivas** [tokuhirom/node-perl#12]
Hi, I tried installing this node module with NodeJS version 5.9.0 and Perl version 5.18.2 compiled with flags specified in this repo's README. I also have `sudo apt-get install libperl-dev` installed. I get the following errors when I do npm install. Please help me here:

```
../src/perl_bindings.cc: In static member function ‘static v8::Handle<v8::Value> NodePerlMethod::callList(const int&)’:
../src/perl_bindings.cc:197:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make: *** [Release/obj.target/perl/src/perl_bindings.o] Error 1
make: Leaving directory `/home/user/project/node_modules/perl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/home/user/.nvm/versions/node/v5.9.0/bin/node" "/home/user/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/user/project/node_modules/perl
gyp ERR! node -v v5.9.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN sem3-url-to-sku@1.0.0 No repository field.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/user/.nvm/versions/node/v5.9.0/bin/node" "/home/user/.nvm/versions/node/v5.9.0/bin/npm" "install" "perl"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! perl@1.5.0 install: `node-gyp clean ; node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the perl@1.5.0 install script 'node-gyp clean ; node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the perl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean ; node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs perl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls perl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/project/npm-debug.log
```

**Comment by kidambisrinivas** [comment]
Worked with 

`sudo npm install perl`

somehow. I dont understand why sudo is required though. But that solved the problem for me.
